### ISSUE TITLE
Neuron's output weights

### ISSUE THREAD

**Issue by pbaravik** [Patryk27/website#18]
https://github.com/Patryk27/website/blob/e2f11b939fbf6984816e0d5366cd4484073acff9/src/content/posts/learning-to-fly-pt2/body.html#L332

Wouldn't it be more correct to state that a neuron applies weights to its inputs, instead?

**Comment by Patryk27** [comment]
Fair point!

I think input weights could be the more intuitive approach here (otherwise, with output weights, the weights on the final layer don't do much) - it shouldn't affect the calculations or network's performance that much in this case, so I think I'll leave the articles as they are (redoing the sketches would take a while 😅), but thanks for reporting!
